services:
  namenode:
    build:
      context: .
      dockerfile: namenode/Dockerfile
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - hadoopnet

  datanode1:
    build:
      context: .
      dockerfile: datanode/Dockerfile
    container_name: datanode1
    hostname: datanode1
    volumes:
      - datanode1_data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoopnet

  datanode2:
    build:
      context: .
      dockerfile: datanode/Dockerfile
    container_name: datanode2
    hostname: datanode2
    volumes:
      - datanode2_data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoopnet

  datanode3:
    build:
      context: .
      dockerfile: datanode/Dockerfile
    container_name: datanode3
    hostname: datanode3
    volumes:
      - datanode3_data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoopnet

volumes:
  namenode_data:
  datanode1_data:
  datanode2_data:
  datanode3_data:

networks:
  hadoopnet:
    driver: bridge