# TYPE  DATABASE   USER        ADDRESS          METHOD

# Local
local   all        all                         trust
host    all        all         127.0.0.1/32     trust

# Permitir conexiones dentro de la red docker
host    all        all         0.0.0.0/0        md5

# Permitir replicación (usuario replicator) desde la red docker
host    replication replicator 0.0.0.0/0        md5