# Conexiones
listen_addresses = '*'
port = 5432

# WAL / Replicación física (streaming replication)
wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
wal_keep_size = 256MB

# Recomendado para el lab (seguro para pruebas; en prod se afina)
hot_standby = on

# Logging básico para ver qué pasa
logging_collector = on
log_connections = on
log_disconnections = on
log_statement = 'none'