# La réplica escucha en 5432 dentro del contenedor
listen_addresses = '*'
port = 5432

# Permite consultas de solo lectura mientras replica (hot standby)
hot_standby = on

# Logging básico
logging_collector = on
log_connections = on
log_disconnections = on